import React, { useState } from "react";
import { SectionHeader } from "./BiasOverview";

// ─── Gemini Advisory Panel ────────────────────────────────────────────────────
function GeminiAdvisory({ sessionId }) {
  const [status, setStatus] = useState("idle"); // idle | loading | done | error
  const [advisory, setAdvisory] = useState(null);
  const [errorMsg, setErrorMsg] = useState("");
  const API = import.meta.env.VITE_API_URL;

  const fetchAdvisory = async () => {
    setStatus("loading");
    setErrorMsg("");
    try {
      const res = await fetch(`${API}/gemini-advisory/${sessionId}`)
      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.detail || "Request failed");
      }
      const data = await res.json();
      setAdvisory(data);
      setStatus("done");
    } catch (e) {
      setErrorMsg(e.message);
      setStatus("error");
    }
  };

  // ── Idle state ──────────────────────────────────────────────────────────────
  if (status === "idle") {
    return (
      <div style={gStyles.idleCard}>
        <div style={gStyles.geminiLogo}>
          <GeminiIcon />
        </div>
        <div style={gStyles.idleContent}>
          <div style={gStyles.idleTitle}>Gemini AI Advisory</div>
          <div style={gStyles.idleDesc}>
            Get an AI-powered plain-language analysis of your bias audit — including legal risk
            assessment, actionable recommendations, and compliance commentary generated by
            Google Gemini 1.5 Flash.
          </div>
          <div style={gStyles.idleTags}>
            {["Legal Risk", "Plain English", "Prioritised Actions", "EU AI Act", "EEOC 4/5ths"].map(t => (
              <span key={t} style={gStyles.tag}>{t}</span>
            ))}
          </div>
        </div>
        <button style={gStyles.cta} onClick={fetchAdvisory}>
          <GeminiIcon size={16} />
          <span>Get AI Advisory</span>
          <span style={gStyles.ctaArrow}>→</span>
        </button>
      </div>
    );
  }

  // ── Loading state ───────────────────────────────────────────────────────────
  if (status === "loading") {
    return (
      <div style={gStyles.loadingCard}>
        <div style={gStyles.pulseRing} />
        <GeminiIcon size={32} />
        <div style={gStyles.loadingText}>Gemini is analysing your bias audit…</div>
        <div style={gStyles.loadingSteps}>
          {["Reading fairness metrics", "Assessing legal exposure", "Generating recommendations"].map((s, i) => (
            <div key={s} style={{ ...gStyles.loadingStep, animationDelay: `${i * 0.4}s` }}>
              <span style={gStyles.loadingDot} />
              {s}
            </div>
          ))}
        </div>
      </div>
    );
  }

  // ── Error state ─────────────────────────────────────────────────────────────
  if (status === "error") {
    return (
      <div style={gStyles.errorCard}>
        <span style={{ fontSize: 28 }}>⚠</span>
        <div style={gStyles.errorTitle}>Advisory Failed</div>
        <div style={gStyles.errorMsg}>{errorMsg}</div>
        <button style={gStyles.retryBtn} onClick={fetchAdvisory}>Try Again</button>
      </div>
    );
  }

  // ── Done state ──────────────────────────────────────────────────────────────
  const { summary, legal_risk, recommendations = [], improvements, concerns } = advisory;
  const riskColor = {
    HIGH: "#ef4444", CRITICAL: "#ef4444",
    MEDIUM: "#f97316",
    LOW: "#22c55e",
  }[String(legal_risk?.level || "").toUpperCase()] || "#6366f1";

  return (
    <div style={gStyles.resultWrap}>
      {/* Header */}
      <div style={gStyles.resultHeader}>
        <div style={gStyles.resultHeaderLeft}>
          <GeminiIcon size={20} />
          <span style={gStyles.resultHeaderTitle}>Gemini AI Advisory</span>
        </div>
        <button style={gStyles.rerunBtn} onClick={() => { setStatus("idle"); setAdvisory(null); }}>
          ↺ Re-run
        </button>
      </div>

      {/* Summary */}
      <div style={gStyles.summaryCard}>
        <div style={gStyles.summaryLabel}>Plain-Language Summary</div>
        <div style={gStyles.summaryText}>{summary}</div>
      </div>

      {/* Legal Risk */}
      {legal_risk && (
        <div style={{ ...gStyles.legalCard, borderColor: riskColor + "40", background: riskColor + "08" }}>
          <div style={gStyles.legalLeft}>
            <span style={{ fontSize: 22 }}>⚖</span>
            <div>
              <div style={gStyles.legalLabel}>Legal Risk Assessment</div>
              <div style={{ ...gStyles.legalLevel, color: riskColor }}>
                {legal_risk.level} RISK
              </div>
            </div>
          </div>
          <div style={gStyles.legalDetail}>{legal_risk.detail || legal_risk.summary}</div>
        </div>
      )}

      {/* Recommendations */}
      {recommendations.length > 0 && (
        <div style={gStyles.recSection}>
          <div style={gStyles.recSectionTitle}>Prioritised Recommendations</div>
          <div style={gStyles.recGrid}>
            {recommendations.map((r, i) => {
              const pColor = {
                HIGH: "#ef4444", CRITICAL: "#ef4444",
                MEDIUM: "#f59e0b",
                LOW: "#22c55e",
              }[String(r.priority || "").toUpperCase()] || "#6366f1";
              return (
                <div key={i} style={{ ...gStyles.recCard, borderLeftColor: pColor }}>
                  <div style={gStyles.recTop}>
                    <span style={{ ...gStyles.recBadge, color: pColor, borderColor: pColor + "40", background: pColor + "10" }}>
                      {r.priority}
                    </span>
                    <span style={gStyles.recNum}>#{i + 1}</span>
                  </div>
                  <div style={gStyles.recAction}>{r.action}</div>
                  <div style={gStyles.recReason}>{r.reason}</div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Improvements & Concerns */}
      <div style={gStyles.splitRow}>
        {improvements && (
          <div style={{ ...gStyles.splitCard, borderColor: "#22c55e30", background: "#22c55e08" }}>
            <div style={{ ...gStyles.splitLabel, color: "#22c55e" }}>✦ What Improved</div>
            <div style={gStyles.splitText}>{improvements}</div>
          </div>
        )}
        {concerns && (
          <div style={{ ...gStyles.splitCard, borderColor: "#f9731630", background: "#f9731608" }}>
            <div style={{ ...gStyles.splitLabel, color: "#f97316" }}>⚠ Remaining Concerns</div>
            <div style={gStyles.splitText}>{concerns}</div>
          </div>
        )}
      </div>

      {/* Footer */}
      <div style={gStyles.footer}>
        <GeminiIcon size={12} />
        Generated by Google Gemini 1.5 Flash · For informational purposes only
      </div>
    </div>
  );
}

// ─── Gemini Icon SVG ──────────────────────────────────────────────────────────
function GeminiIcon({ size = 24 }) {
  return (
    <svg width={size} height={size} viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="gGrad" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stopColor="#4285F4" />
          <stop offset="50%" stopColor="#9B72CB" />
          <stop offset="100%" stopColor="#EA4335" />
        </linearGradient>
      </defs>
      <path
        d="M14 2C14 2 14 10.5 7 14C14 17.5 14 26 14 26C14 26 14 17.5 21 14C14 10.5 14 2 14 2Z"
        fill="url(#gGrad)"
      />
    </svg>
  );
}

// ─── Gemini panel styles ──────────────────────────────────────────────────────
const gStyles = {
  idleCard: {
    display: "flex",
    alignItems: "center",
    gap: 20,
    background: "linear-gradient(135deg, rgba(66,133,244,0.06) 0%, rgba(155,114,203,0.08) 50%, rgba(234,67,53,0.06) 100%)",
    border: "1px solid rgba(99,102,241,0.25)",
    borderRadius: 14,
    padding: "24px 28px",
    flexWrap: "wrap",
  },
  geminiLogo: { flexShrink: 0 },
  idleContent: { flex: 1, minWidth: 240 },
  idleTitle: { fontSize: 15, fontWeight: 800, color: "#e2e8f0", marginBottom: 6, letterSpacing: "0.01em" },
  idleDesc: { fontSize: 13, color: "#64748b", lineHeight: 1.7, fontFamily: "system-ui, sans-serif", marginBottom: 12 },
  idleTags: { display: "flex", gap: 8, flexWrap: "wrap" },
  tag: {
    fontSize: 10,
    padding: "3px 10px",
    borderRadius: 20,
    border: "1px solid rgba(99,102,241,0.3)",
    color: "#a5b4fc",
    letterSpacing: "0.06em",
    background: "rgba(99,102,241,0.08)",
  },
  cta: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "linear-gradient(135deg, #4285F4, #9B72CB)",
    border: "none",
    borderRadius: 10,
    padding: "12px 22px",
    color: "#fff",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    letterSpacing: "0.02em",
    flexShrink: 0,
  },
  ctaArrow: { fontSize: 16 },
  loadingCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
    padding: "40px 24px",
    background: "rgba(15,23,42,0.6)",
    border: "1px solid rgba(99,102,241,0.2)",
    borderRadius: 14,
    position: "relative",
    overflow: "hidden",
  },
  pulseRing: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: 160,
    height: 160,
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(99,102,241,0.12) 0%, transparent 70%)",
    animation: "pulse 2s ease-in-out infinite",
  },
  loadingText: { fontSize: 14, color: "#a5b4fc", fontWeight: 600, letterSpacing: "0.03em" },
  loadingSteps: { display: "flex", flexDirection: "column", gap: 8, marginTop: 4 },
  loadingStep: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 12,
    color: "#475569",
    fontFamily: "system-ui, sans-serif",
    animation: "fadeIn 0.5s ease forwards",
    opacity: 0,
  },
  loadingDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #4285F4, #9B72CB)",
    flexShrink: 0,
  },
  errorCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
    padding: 32,
    background: "rgba(239,68,68,0.05)",
    border: "1px solid rgba(239,68,68,0.2)",
    borderRadius: 14,
  },
  errorTitle: { fontSize: 15, fontWeight: 700, color: "#ef4444" },
  errorMsg: { fontSize: 12, color: "#64748b", fontFamily: "monospace", textAlign: "center", maxWidth: 400 },
  retryBtn: {
    marginTop: 8,
    padding: "9px 20px",
    background: "rgba(239,68,68,0.1)",
    border: "1px solid rgba(239,68,68,0.3)",
    borderRadius: 8,
    color: "#ef4444",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    letterSpacing: "0.05em",
  },
  resultWrap: { display: "flex", flexDirection: "column", gap: 16 },
  resultHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  resultHeaderLeft: { display: "flex", alignItems: "center", gap: 10 },
  resultHeaderTitle: { fontSize: 15, fontWeight: 800, color: "#e2e8f0", letterSpacing: "0.01em" },
  rerunBtn: {
    fontSize: 11,
    padding: "5px 14px",
    background: "rgba(99,102,241,0.08)",
    border: "1px solid rgba(99,102,241,0.2)",
    borderRadius: 8,
    color: "#a5b4fc",
    cursor: "pointer",
    letterSpacing: "0.05em",
  },
  summaryCard: {
    background: "rgba(15,23,42,0.8)",
    border: "1px solid rgba(99,102,241,0.15)",
    borderRadius: 12,
    padding: "20px 24px",
  },
  summaryLabel: { fontSize: 10, letterSpacing: "0.12em", color: "#6366f1", textTransform: "uppercase", fontWeight: 700, marginBottom: 10 },
  summaryText: { fontSize: 14, color: "#cbd5e1", lineHeight: 1.8, fontFamily: "system-ui, sans-serif" },
  legalCard: {
    display: "flex",
    gap: 20,
    border: "1px solid",
    borderRadius: 12,
    padding: "18px 24px",
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  legalLeft: { display: "flex", gap: 14, alignItems: "center", flexShrink: 0 },
  legalLabel: { fontSize: 10, letterSpacing: "0.1em", color: "#64748b", textTransform: "uppercase", fontWeight: 700, marginBottom: 4 },
  legalLevel: { fontSize: 14, fontWeight: 800, letterSpacing: "0.06em" },
  legalDetail: { fontSize: 13, color: "#94a3b8", lineHeight: 1.7, fontFamily: "system-ui, sans-serif", flex: 1, minWidth: 200 },
  recSection: {},
  recSectionTitle: { fontSize: 13, fontWeight: 700, color: "#e2e8f0", marginBottom: 12, letterSpacing: "0.03em" },
  recGrid: { display: "flex", flexDirection: "column", gap: 10 },
  recCard: {
    background: "rgba(15,23,42,0.7)",
    border: "1px solid rgba(99,102,241,0.1)",
    borderLeft: "3px solid",
    borderRadius: "0 10px 10px 0",
    padding: "14px 18px",
  },
  recTop: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 6 },
  recBadge: {
    fontSize: 9,
    padding: "3px 10px",
    borderRadius: 20,
    border: "1px solid",
    letterSpacing: "0.12em",
    fontWeight: 700,
    textTransform: "uppercase",
  },
  recNum: { fontSize: 11, color: "#334155", fontFamily: "monospace" },
  recAction: { fontSize: 13, color: "#e2e8f0", fontWeight: 700, marginBottom: 5 },
  recReason: { fontSize: 12, color: "#64748b", lineHeight: 1.65, fontFamily: "system-ui, sans-serif" },
  splitRow: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 },
  splitCard: { border: "1px solid", borderRadius: 12, padding: "18px 20px" },
  splitLabel: { fontSize: 12, fontWeight: 700, letterSpacing: "0.05em", marginBottom: 10 },
  splitText: { fontSize: 13, color: "#64748b", lineHeight: 1.7, fontFamily: "system-ui, sans-serif" },
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    color: "#334155",
    paddingTop: 4,
    fontFamily: "system-ui, sans-serif",
    letterSpacing: "0.02em",
  },
};

// ─── Main BiasExplainer Component ─────────────────────────────────────────────
export default function BiasExplainer({ data, sessionId }) {
  const { before, after, comparison, protected_attributes } = data;

  const dpd       = before.metrics.demographic_parity_difference;
  const eov       = before.metrics.equalized_odds_violation;
  const flipRate  = before.instability.flip_rate;
  const dir       = before.metrics.disparate_impact_ratio;
  const fs        = before.fairness_score;

  const severity      = fs < 0.3 ? "critical" : fs < 0.5 ? "high" : fs < 0.7 ? "moderate" : "low";
  const severityColor = { critical: "#ef4444", high: "#f97316", moderate: "#f59e0b", low: "#22c55e" }[severity];
  const severityLabel = severity.toUpperCase();

  const worstGroup = before.bias_table[0];
  const bestGroup  = before.bias_table[before.bias_table.length - 1];

  const findings = [
    {
      icon: "⚠",
      color: "#ef4444",
      title: "Intersectional Bias Detected",
      body: `The model shows a ${(dpd * 100).toFixed(1)} percentage-point gap in positive outcome rates between 
        the most and least favored demographic groups. The most advantaged group (${bestGroup?.group}) 
        receives positive outcomes ${(bestGroup?.positive_rate * 100).toFixed(1)}% of the time, 
        compared to only ${(worstGroup?.positive_rate * 100).toFixed(1)}% for the most disadvantaged 
        group (${worstGroup?.group}). This ${(dpd * 100).toFixed(1)}pp gap is ${dpd > 0.5 ? "severe" : dpd > 0.2 ? "significant" : "mild"} and 
        indicates the model's decisions are strongly correlated with protected attributes.`,
    },
    {
      icon: "⬡",
      color: "#6366f1",
      title: "Counterfactual Discrimination Found",
      body: `When we create "counterfactual twins" — identical individuals except for their protected 
        attribute — ${(flipRate * 100).toFixed(1)}% of predictions change. This means ${Math.round(flipRate * data.n_rows)} 
        people out of ${data.n_rows.toLocaleString()} would receive a different outcome purely because 
        of their gender or race, not because of their qualifications. The Individual Discrimination 
        Index (IDI) of ${before.instability.idi.toFixed(3)} confirms that the model's confidence 
        shifts substantially when only protected attributes change.`,
    },
    {
      icon: "⚖",
      color: "#f59e0b",
      title: "Equalized Odds Violation",
      body: `The model's True Positive Rate (sensitivity) and False Positive Rate (specificity) differ 
        significantly across groups (violation: ${(eov * 100).toFixed(1)}pp). This means equally 
        qualified individuals from different demographic groups do not have equal chances of being 
        correctly identified for positive outcomes. The 4/5ths disparate impact test 
        ${dir < 0.8
          ? `also fails (ratio: ${dir.toFixed(3)} < 0.8 threshold), indicating legally significant disparate impact under many fairness regulations`
          : `passes (ratio: ${dir.toFixed(3)} ≥ 0.8)`}.`,
    },
    {
      icon: "✦",
      color: "#22c55e",
      title: "Mitigation Results",
      body: `After applying Inverse Probability Weighting (IPW) with iterative disparity correction, 
        the Composite Fairness Score improved from ${(before.fairness_score * 100).toFixed(1)}% to 
        ${(after.fairness_score * 100).toFixed(1)}% (+${(comparison.fairness_gain * 100).toFixed(1)}pts). 
        Demographic parity difference dropped by ${comparison.dpd_reduction}%, equalized odds violation 
        reduced by ${comparison.eov_reduction}%, and the flip rate fell from ${(before.instability.flip_rate * 100).toFixed(1)}% 
        to ${(after.instability.flip_rate * 100).toFixed(1)}%. The accuracy cost was minimal at 
        ${(comparison.accuracy_cost * 100).toFixed(2)} percentage points, demonstrating that 
        fairness and performance are not mutually exclusive.`,
    },
  ];

  const staticRecs = [
    {
      priority: "Critical",
      color: "#ef4444",
      action: "Deploy only the debiased model",
      detail: `The baseline model shows unacceptable bias (fairness score ${(fs * 100).toFixed(1)}%). 
        The mitigated model should be used for any real decisions.`,
    },
    {
      priority: "High",
      color: "#f97316",
      action: "Monitor ongoing fairness in production",
      detail: `Even after mitigation, disparate impact ratio (${after.metrics.disparate_impact_ratio.toFixed(3)}) 
        remains below the 0.80 threshold. Continuous monitoring is required.`,
    },
    {
      priority: "High",
      color: "#f59e0b",
      action: "Investigate data collection bias",
      detail: `Historical bias in training data is a root cause. Audit data collection practices 
        to prevent perpetuating systemic inequities in future model versions.`,
    },
    {
      priority: "Medium",
      color: "#6366f1",
      action: "Extend to additional protected attributes",
      detail: `Current analysis covers ${protected_attributes.join(" and ")}. 
        Expand to disability status, age, socioeconomic background, and their intersections.`,
    },
    {
      priority: "Medium",
      color: "#6366f1",
      action: "Explore in-processing debiasing",
      detail: "IPW is a post-hoc technique. Adversarial debiasing or fairness constraints during training may achieve better joint fairness-utility tradeoffs.",
    },
    {
      priority: "Low",
      color: "#22c55e",
      action: "Document and disclose bias audit findings",
      detail: "Transparency about known limitations and mitigation efforts is both ethically important and increasingly required by regulation (EU AI Act, etc.).",
    },
  ];

  return (
    <div style={styles.wrap}>
      {/* Keyframe styles injected once */}
      <style>{`
        @keyframes pulse {
          0%, 100% { transform: translate(-50%, -50%) scale(1); opacity: 0.6; }
          50% { transform: translate(-50%, -50%) scale(1.4); opacity: 0.2; }
        }
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(6px); }
          to   { opacity: 1; transform: translateY(0); }
        }
      `}</style>

      <SectionHeader
        title="Bias Explanation Panel"
        subtitle="Plain-language interpretation of fairness audit results for non-technical stakeholders"
      />

      {/* ── Gemini AI Advisory (top, prominent) ─────────────────────────── */}
      <GeminiAdvisory sessionId={sessionId} />

      {/* ── Divider ─────────────────────────────────────────────────────── */}
      <div style={styles.divider}>
        <div style={styles.dividerLine} />
        <span style={styles.dividerLabel}>Static Audit Findings</span>
        <div style={styles.dividerLine} />
      </div>

      {/* ── Severity banner ──────────────────────────────────────────────── */}
      <div style={{ ...styles.banner, borderColor: severityColor + "50", background: severityColor + "0d" }}>
        <div style={styles.bannerLeft}>
          <span style={{ color: severityColor, fontSize: 28, marginRight: 12 }}>
            {severity === "critical" ? "🚨" : severity === "high" ? "⚠️" : severity === "moderate" ? "⚡" : "✅"}
          </span>
          <div>
            <div style={{ ...styles.bannerTitle, color: severityColor }}>
              {severityLabel} BIAS LEVEL DETECTED
            </div>
            <div style={styles.bannerSub}>
              Pre-mitigation composite fairness score: {(fs * 100).toFixed(1)}% / 100%
            </div>
          </div>
        </div>
        <div style={styles.bannerRight}>
          <div style={styles.bannerMetrics}>
            <span>DPD: <strong style={{ color: severityColor }}>{(dpd * 100).toFixed(1)}pp</strong></span>
            <span>Flip: <strong style={{ color: severityColor }}>{(flipRate * 100).toFixed(1)}%</strong></span>
            <span>EOV: <strong style={{ color: severityColor }}>{(eov * 100).toFixed(1)}pp</strong></span>
          </div>
        </div>
      </div>

      {/* ── Findings grid ────────────────────────────────────────────────── */}
      <div style={styles.findingsGrid}>
        {findings.map(f => (
          <div key={f.title} style={{ ...styles.findingCard, borderColor: f.color + "30" }}>
            <div style={{ color: f.color, fontSize: 24, marginBottom: 10 }}>{f.icon}</div>
            <h3 style={{ ...styles.findingTitle, color: f.color }}>{f.title}</h3>
            <p style={styles.findingBody}>{f.body}</p>
          </div>
        ))}
      </div>

      {/* ── Analogy box ──────────────────────────────────────────────────── */}
      <div style={styles.analogyBox}>
        <div style={styles.analogyTitle}>🎓 What This Means in Practice</div>
        <div style={styles.analogyText}>
          Imagine {data.n_rows.toLocaleString()} job applications being scored by this AI system.
          Under the original model, <strong style={{ color: "#ef4444" }}>{Math.round(before.instability.flip_rate * data.n_rows).toLocaleString()} applicants</strong> would
          receive a different hiring decision if only their gender or race were different — not their
          skills, experience, or education. That's direct algorithmic discrimination. After mitigation,
          this drops to approximately <strong style={{ color: "#22c55e" }}>{Math.round(after.instability.flip_rate * data.n_rows).toLocaleString()} applicants</strong> — 
          a {comparison.flip_rate_reduction}% reduction in discriminatory decisions. However, complete
          fairness was not achieved, and this system should not be deployed without further oversight.
        </div>
      </div>

      {/* ── Static recommendations ───────────────────────────────────────── */}
      <div style={styles.recBox}>
        <h3 style={styles.recTitle}>Actionable Recommendations</h3>
        <div style={styles.recList}>
          {staticRecs.map(r => (
            <div key={r.action} style={styles.recRow}>
              <span style={{ ...styles.recPriority, color: r.color, borderColor: r.color + "40", background: r.color + "10" }}>
                {r.priority}
              </span>
              <div>
                <div style={styles.recAction}>{r.action}</div>
                <div style={styles.recDetail}>{r.detail}</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ─── Static section styles (unchanged from original) ─────────────────────────
const styles = {
  wrap: { display: "flex", flexDirection: "column", gap: 24 },
  divider: { display: "flex", alignItems: "center", gap: 14, margin: "4px 0" },
  dividerLine: { flex: 1, height: 1, background: "rgba(99,102,241,0.12)" },
  dividerLabel: { fontSize: 10, color: "#334155", letterSpacing: "0.12em", textTransform: "uppercase", whiteSpace: "nowrap" },
  banner: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    border: "1px solid",
    borderRadius: 12,
    padding: "20px 24px",
    flexWrap: "wrap",
    gap: 16,
  },
  bannerLeft: { display: "flex", alignItems: "center" },
  bannerTitle: { fontSize: 15, fontWeight: 800, letterSpacing: "0.08em", marginBottom: 4 },
  bannerSub: { fontSize: 12, color: "#64748b", fontFamily: "system-ui, sans-serif" },
  bannerRight: {},
  bannerMetrics: { display: "flex", gap: 20, fontSize: 12, color: "#64748b", fontFamily: "monospace" },
  findingsGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 },
  findingCard: {
    background: "rgba(15,23,42,0.7)",
    border: "1px solid",
    borderRadius: 12,
    padding: 24,
  },
  findingTitle: { fontSize: 14, fontWeight: 700, margin: "0 0 10px", letterSpacing: "0.02em" },
  findingBody: { fontSize: 13, color: "#64748b", lineHeight: 1.75, margin: 0, fontFamily: "system-ui, sans-serif" },
  analogyBox: {
    background: "rgba(99,102,241,0.06)",
    border: "1px solid rgba(99,102,241,0.2)",
    borderRadius: 12,
    padding: 24,
  },
  analogyTitle: { fontSize: 14, fontWeight: 700, color: "#a5b4fc", marginBottom: 12 },
  analogyText: { fontSize: 14, color: "#64748b", lineHeight: 1.8, fontFamily: "system-ui, sans-serif" },
  recBox: {
    background: "rgba(15,23,42,0.7)",
    border: "1px solid rgba(99,102,241,0.12)",
    borderRadius: 12,
    padding: 24,
  },
  recTitle: { margin: "0 0 20px", fontSize: 15, color: "#e2e8f0", fontWeight: 700 },
  recList: { display: "flex", flexDirection: "column", gap: 16 },
  recRow: { display: "flex", gap: 16, alignItems: "flex-start" },
  recPriority: {
    fontSize: 10,
    padding: "4px 10px",
    borderRadius: 20,
    border: "1px solid",
    letterSpacing: "0.1em",
    whiteSpace: "nowrap",
    marginTop: 2,
    flexShrink: 0,
  },
  recAction: { fontSize: 13, color: "#e2e8f0", fontWeight: 700, marginBottom: 4 },
  recDetail: { fontSize: 12, color: "#64748b", lineHeight: 1.6, fontFamily: "system-ui, sans-serif" },
};
